
INTALL_K3S_SCRIPT = <<-COMMANDS
  # curl -sfL https://get.k3s.io | sh -
  echo "Running"
COMMANDS

VMS = [
  { hostname: 'achaaouiS', ip: '192.168.56.110', ssh_port: 4242 },
  { hostname: 'achaaouiSW', ip: '192.168.56.111', ssh_port: 2223 },
]

Vagrant.configure("2") do |config|
  config.vm.box = "fedora/40-cloud-base"
  config.vm.box_check_update = true
  config.vm.synced_folder "./data", "/shared_data", owner: "www-data", group: "www-data"

  config.vm.provider "qemu" do |provider|
    provider.arch = "x86_64"
    provider.machine = "q35"
    provider.cpu = "max"
    provider.net_device = "virtio-net-pci"
  end

  VMS.each do |entry|
    config.vm.define entry[:hostname] do |conf|
      conf.vm.network :private_network, ip: entry[:ip]
      conf.vm.network :forwarded_port, guest: 22, host: entry[:ssh_port]
      conf.vm.hostname = entry[:hostname]
    end
  end

  config.vm.provision "shell", inline: <<-SHELL
    # dnf install vim
  SHELL
  config.vm.provision "shell", inline: INTALL_K3S_SCRIPT
end
