
INTALL_K3S_SCRIPT = <<-COMMANDS
  curl -sfL https://get.k3s.io | sh -
COMMANDS

VMS = [
  { hostname: 'achaaouiS', ip: '192.168.56.110' },
  { hostname: 'achaaouiSW', ip: '192.168.56.111' },
]

Vagrant.configure("2") do |config|
  config.vm.box = "fedora/40-cloud-base"
  config.vm.box_check_update = true
  config.vm.synced_folder "../data", "/shared_data", owner: "www-data", group: "www-data"

  config.vm.provider "virtualbox" do |virtualbox|
    virtualbox.memory = 512
    virtualbox.cpus = 1
  end

  VMS.each do |entry|
    config.vm.define entry[:hostname] do |conf|
      conf.vm.network "private_network", id: entry[:ip]
      conf.vm.hostname = entry[:hostname]
    end
  end

  config.vm.provision "shell", inline: <<-SHELL
    # dnf install vim
  SHELL
  config.vm.provision "shell", inline: INTALL_K3S_SCRIPT
end
